name: geoab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.25.1
  - scipy=1.11.1
  - pandas=2.1.1
  - scikit-learn=1.3.0
  - rdkit=2023.3.2
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - async-timeout=4.0.3
  - attrs=23.1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates
  - charset-normalizer=3.2.0
  - click=8.1.7
  - contourpy=1.1.1
  - cycler=0.11.0
  - dill=0.3.7
  - filelock=3.11.0
  - frozenlist=1.4.0
  - idna=3.4
  - importlib-metadata=6.8.0
  - keyutils=1.6.1
  - krb5
  - ld_impl_linux-64
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.3.0
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.1.0
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libnuma=2.0.16
  - libopenblas=0.3.24
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - multidict=6.0.4
  - multiprocess=0.70.15
  - ncurses=6.4
  - openssl>=3.1.3,<4.0a0
  - packaging=23.1
  - pysocks=1.7.1
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=3.3.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - regex=2023.8.8
  - requests=2.31.0
  - s2n=1.3.51
  - safetensors=0.3.3
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.10
  - tk=8.6.12
  - tokenizers=0.13.3
  - typing_extensions=4.8.0
  - tzdata=2023c
  - ucx=1.14.1
  - wheel=0.40.0
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zipp=3.17.0
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - astor==0.8.1
      - astropy==5.3.3
      - biopython==1.81
      - biotite==0.38.0
      - cachetools==5.3.1
      - certifi==2023.5.7
      - cloudpickle==2.2.1
      - cmake==3.26.4
      - contextlib2==21.6.0
      - e3nn==0.5.4
      - easydict==1.10
      - fsspec==2023.9.2
      - datasets==2.*
      - fonttools==4.42.1
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.56.0
      - jinja2==3.1.2
      - joblib==1.3.1
      - json-tricks==3.17.3
      - kiwisolver==1.4.5
      - lightning-utilities==0.9.0
      - lit==16.0.6
      - lmdb==1.4.1
      - markdown==3.4.3
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - mpmath==1.3.0
      - msgpack==1.0.6
      - networkx==3.1
      - nni==3.0
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - opt-einsum-fx==0.1.4
      - pillow==10.0.0
      - prettytable==3.9.0
      - protobuf
